### PR TITLE
fixed img responsive

### PR DESCRIPTION
**Pull request by madmaxWMFU**
Issue #12

### CODE REVIEW

**Comment by degittester** [comment]
You may crop the image or you can use a different image for Step-3

**Comment by madmaxWMFU** [comment]
How did you check this? Because I have corrected all the images. If you just substituted just CSS for checking yourself, then correct the HTML by removing the extra DIV element in the third step with the picture.

**Comment by madmaxWMFU** [comment]
CPT2110160918-924x428

**Comment by degittester** [comment]
> How did you check this? Because I have corrected all the images. If you just substituted just CSS for checking yourself, then correct the HTML by removing the extra DIV element in the third step with the picture.

Actually, I earlier copied your code in my local system. Maybe because of the browser it was showing the error.

**Pull request merged**
